spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/elearning
    username: postgres
    password: danel
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml



server:
  port: 8080

jwt:
  secret: mysupersecretkey12345